<?php
header('Cache-Control: no-store, private, max-age=0');
header('X-Robots-Tag: noindex, nofollow, noarchive');
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; frame-src 'self' about:; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SEO Studio · Daniel Solar</title><link rel="icon" href="/favicon.svg"><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Jost:wght@400;500;600&family=Space+Mono&display=swap" rel="stylesheet"><link rel="stylesheet" href="dashboard.css?v=1"><script src="dashboard.js?v=1" defer></script></head>
<body>
<header class="topbar"><a class="brand" href="./"><img src="/favicon.svg" width="38" height="38" alt=""><span>Daniel Solar<small>ENGINEERING &amp; DESIGN</small></span></a><span class="studio-label">SEO STUDIO <span class="pill">SEO-only access</span></span><button id="logout" class="quiet" hidden>Sign out</button></header>
<div id="notice" class="notice" role="status" aria-live="polite" hidden></div>
<main id="login-view" class="login-shell">
<section class="login-intro"><div class="eyebrow">A CLEARER PATH TO DISCOVERY</div><h1>Your expertise.<br>A little easier<br>to find.</h1><p>Keep your website’s words and search details up to date, one page at a time.</p><div class="intro-rule"></div><small>THE DANIEL SOLAR CONTENT WORKSPACE</small></section>
<form id="login-form" class="login-card"><div class="eyebrow">WELCOME BACK</div><h2>Sign in to SEO Studio</h2><p>A dedicated workspace for your website content.</p><label for="email">Email address</label><input id="email" type="email" autocomplete="username" required maxlength="254"><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required maxlength="1024"><button class="primary" type="submit">Sign in <span aria-hidden="true">→</span></button><small>Your SEO account is separate from any site admin account.</small></form>
</main>
<main id="workspace" hidden>
<section class="workspace-head"><div><div class="eyebrow">WORDS THAT WORK</div><h1>Your website, well presented.</h1><p>Edit your content. Preview your work. Publish with confidence.</p></div><!-- <button id="new-page" class="primary">+ Create a page</button> --></section>
<section class="hosting-bar"><span id="hosting-status">Hosting check required before publishing.</span><button id="probe" class="quiet">Check hosting</button><details id="hosting-details"><summary>Check details</summary><ul id="hosting-results"></ul></details></section>
<div class="work-grid"><aside class="page-sidebar"><div class="sidebar-title"><h2>Website pages</h2><span id="page-count" class="count"></span></div><label for="page-search" class="sr-only">Find a page</label><input id="page-search" type="search" placeholder="Find a page…"><nav id="page-list" aria-label="Website pages"></nav><div class="sidebar-note">Changes stay in your draft until you select <strong>Save &amp; publish</strong>.</div></aside>
<section class="editor-panel"><div id="empty" class="empty"><span class="eyebrow">LET’S GET STARTED</span><h2>Choose a page to edit</h2><p>Select a page on the left or create something new.</p></div>
<form id="editor" hidden><div class="editor-title"><div><div class="eyebrow" id="editor-kicker">PAGE EDITOR</div><h2 id="editor-name"></h2><a id="live-link" target="_blank" rel="noopener">Open published page ↗</a></div><span id="draft-state" class="pill">No unsaved changes</span></div>
<div id="new-fields" hidden class="card"><h3>New page</h3><p>Use a short, descriptive URL. Your page will use the site’s header, footer and design.</p><label for="slug">URL slug</label><div class="slug-input"><span>/</span><input id="slug" placeholder="solar-design-guide" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="80"><span>.html</span></div><label for="heading">Page heading</label><input id="heading" maxlength="200"><label for="body-copy">Page content</label><textarea id="body-copy" rows="9" maxlength="40000" placeholder="Write your page here. Leave a blank line between paragraphs."></textarea></div>
<section class="card"><div class="section-top"><h3>Search appearance</h3><span>01 / SEARCH DETAILS</span></div><p>Help people understand this page in search results.</p><label for="meta-title">Meta title <small id="title-count"></small></label><input id="meta-title" maxlength="200" required><label for="meta-description">Meta description <small id="description-count"></small></label><textarea id="meta-description" rows="3" maxlength="500"></textarea><label for="meta-keywords">Tags / keywords</label><input id="meta-keywords" maxlength="1000" placeholder="solar permits, engineering, plan sets"><small>Separate with commas. Keywords are saved as metadata; they do not guarantee search rankings.</small><div class="search-preview"><span id="search-url"></span><strong id="search-title"></strong><p id="search-description"></p></div></section>
<section id="content-section" class="card"><div class="section-top"><h3>Page text</h3><span>02 / VISIBLE CONTENT</span></div><p>Each field changes only that piece of text. Layout, code and existing link destinations stay intact.</p><label for="text-search" class="sr-only">Find text on this page</label><input id="text-search" type="search" placeholder="Find words on this page…"><div id="text-count" class="field-count"></div><div id="page-fields" class="text-fields"></div><details id="chrome-section"><summary>Header &amp; footer <span id="chrome-count"></span></summary><p>These changes apply to this page only.</p><div id="chrome-fields" class="text-fields"></div></details></section>
<section id="link-section" class="card"><div class="section-top"><h3>Add a page link</h3><span>03 / CONNECT PAGES</span></div><p>Add a link after a piece of text, without replacing existing links. Publish a new page first, then select it here.</p><label class="check-label"><input id="add-link" type="checkbox"> Add a link with this save</label><div id="link-fields" hidden><label for="link-target">Link to page</label><select id="link-target"></select><label for="link-label">Link text</label><input id="link-label" maxlength="160" placeholder="Explore our solar design guide"><label for="link-after">Place after</label><select id="link-after"></select></div></section>
<div class="editor-actions"><button type="button" id="reload" class="quiet">Reload page</button><span id="save-note">Preview before publishing.</span><button type="button" id="preview" class="secondary">Preview draft</button><button type="submit" id="save" class="primary">Save &amp; publish</button></div></form>
</section></div></main>
<dialog id="preview-dialog"><div class="preview-toolbar"><div><strong>Draft preview</strong><small>Not published. Links, forms and popups are restricted in this preview.</small></div><button id="close-preview" class="secondary">Close preview</button></div><iframe id="preview-frame" title="Draft page preview" sandbox="allow-scripts"></iframe></dialog>
<footer class="app-footer"><span>DANIEL SOLAR · SEO STUDIO</span><span>Thoughtful words. Lasting impressions.</span></footer>
</body></html>
